# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HomeWiseLoginFrontend' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HomeWiseLoginFrontend
	pod 'Firebase/Core'

  target 'HomeWiseLoginFrontendTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HomeWiseLoginFrontend-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HomeWiseLoginFrontend-tvOS

  target 'HomeWiseLoginFrontend-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
